# The Docker image that will be used to build your app
image: python:alpine3.19
# Functions that should be executed before the build script is run
before_script:
  - pip install mkdocs
pages:
  script:
    - mkdocs build --verbose --clean
    - mkdocs serve
  artifacts:
    paths:
      - public
  only:
    - master
