---
site_name: Mehrdad's Docs Stack
site_url: https://mehrdad-docs.gitlab.io/docstack
# site_url: https://www.geekfa.net/
site_description: My all project documentation in MD format.
site_author: Mehrdad Qasemkhani
site_dir: public

repo_url: https://gitlab.com/mehrdad-docs/docstack
edit_uri: blob/master/docs/

theme:
  name: material
  # features:
  #   - navigation.tabs
  icon:
    logo: "material/cloud-outline"
  favicon: "img/logo-notext.svg"
  palette:
    scheme: slate
    primary: "teal"
    accent: "green"

extra_css: [extra.css]

plugins:
  - search
