---
site_name: Mehrdad's Docs Stack
site_url: https://mehrdad-drpc.github.io/docstack
# site_url: https://www.geekfa.net/
site_description: My all project documentation in MD format.
site_author: Mehrdad Qasemkhani
site_dir: public

repo_url: https://github.com/mehrdad-drpc/docstack
edit_uri: blob/master/docs/

theme:
  name: material
  # features:
  #   - navigation.tabs
  icon:
    logo: "material/cloud-outline"
    # logo: "img/favicon.ico"
  favicon: "img/favicon.ico"
  palette:
    scheme: slate
    primary: black
    accent: indigo

extra_css: [extra.css]

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
